- name: 选举
  shell: "{{ bin_dir }}/mongo admin --port 27018 --eval 'rs.initiate({_id: \"rs1\", members: [{_id: 0, host: \"{{ ansible_default_ipv4.address }}:27018\"}]})'"

- name: 创建用户
  shell: "{{ bin_dir }}/mongo admin --port 27018 --eval 'db.createUser({user: \"root\", pwd: \"root\", roles: [{role: \"root\", db: \"admin\"}]})'"

- name: 添加其它节点到primary节点
  shell: "{{ bin_dir }}/mongo admin --port 27018 -u root -p root --eval 'rs.add(\"{{ item }}:27018\")'"
  with_items: "{{ groups['shard-secondary'] }}"