- name: 创建相关目录
  file: name={{ item }} state=directory
  with_items:
  - /var/log/mongodb
  - /var/lib/mongodb/config
  - /var/run/mongodb
  - /home/mongodb

- name: 复制配置文件
  template: src=config.conf.j2 dest=/etc/mongo-config.conf

- name: 启动mongodb
  shell: "{{ bin_dir }}/mongod -f /etc/mongo-config.conf"
